# Generated by Django 5.1 on 2024-10-27 04:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now_add=True, null=True)),
                ('image', models.URLField(blank=True, default='https://img.freepik.com/premium-photo/poster-anime-character-with-fiery-background_943629-32000.jpg', null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20)),
                ('mobile', models.CharField(blank=True, max_length=14)),
                ('points', models.IntegerField(blank=True, default=0, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('hometown', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
