# Generated by Django 5.1 on 2024-10-28 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0002_alter_events_cat'),
        ('UserProfiles', '0002_alter_useraccount_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='image',
            field=models.URLField(blank=True, default='https://img.freepik.com/free-photo/androgynous-avatar-non-binary-queer-person_23-2151100211.jpg', null=True),
        ),
        migrations.CreateModel(
            name='UserBooked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('ev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_event', to='Events.events')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
